### ISSUE TITLE
Which technique is being used to detect who picks up specific product?

### ISSUE THREAD

**Issue by ghost** [sa1f/quickshop#27]
I tried to find the details about the technique which you are using to recognize 
1)Who picks up the product
2)Which product is being picked 
I can solve these two problems individually but wants some help how did you approach this problem.

**Comment by sa1f** [comment]
I believe we just did a queue like system, first person in the store is associated with the first product picked.

If the course deadline was longer we would’ve done something along the lines of having another camera, associated with the shelf that faces the user. That way when we detect the user entering the frame, we can associate any product movement with that user. Hope that helps!
